### PR TITLE
French Translation

### PR DESCRIPTION
**Pull request by baptiste-faure1811**
Here comes the French Translation

### CODE REVIEW

**Comment by jordibruin** [comment]
Holy crap that was fast haha!

**Comment by baptiste-faure1811** [comment]
Can't wait for the app :)

**Comment by jordibruin** [comment]
@baptiste-faure1811 I added three more sentences to the file , could you fill those in so I can add your emoji and name to the translator map?

/* TRANSLATOR NAME AND INFO, PLEASE FILL THIS IN SO I CAN ADD YOU TO THE MAP */
/* Translator name (Jordi Bruin)*/
/* What city and country do you live in (Amsterdam, Netherlands) */
/* what's your favorite emoji? (😘) */

**Comment by jordibruin** [comment]
Also, are you on Twitter?

**Pull request merged**
